#!/usr/bin/env sh
# Minimal Gradle wrapper launcher (gradle-wrapper.jar is generated by scripts/bootstrap-gradle-wrapper.sh)

APP_HOME="$(cd "$(dirname "$0")" && pwd)"
WRAPPER_JAR="$APP_HOME/gradle/wrapper/gradle-wrapper.jar"

if [ ! -f "$WRAPPER_JAR" ]; then
  echo "ERROR: $WRAPPER_JAR not found."
  echo "Run: bash scripts/bootstrap-gradle-wrapper.sh"
  exit 1
fi

if [ -n "$JAVA_HOME" ] && [ -x "$JAVA_HOME/bin/java" ]; then
  JAVACMD="$JAVA_HOME/bin/java"
else
  JAVACMD="java"
fi

exec "$JAVACMD"   -Dorg.gradle.appname=gradlew   -classpath "$WRAPPER_JAR"   org.gradle.wrapper.GradleWrapperMain   "$@"
